### ISSUE TITLE
First Pass Tracking Issues

### ISSUE THREAD

**Issue by shawntabrizi** [hamidra/dotdrop#1]
- [x] Show a placeholder page when the front end is not connected to a node telling them this. Will help when sharing this with others that they dont think the UI is broken.

- [x] Claim page and redeem page should be different paths. So maybe the landing page should be: "Create a Gift / Redeem a Gift" with different buttons
- [x] Mailto link should contain the text you generated
- [x] Input Validation, should not be able to generate if data isnt filled
